# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

theme = "congo"
defaultContentLanguage = "en"

enableRobotsTXT = true
paginate = 100
summaryLength = 0
[outputs]
  home = ["HTML", "RSS", "JSON"]

[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "rss"
