languageCode = "de"
languageName = "Deutsch"
languageDirection = "ltr"
weight = 2

[params]
  dateFormat = "2. Jan 2006"
  mainSections = ["essay", "guide", "review", "project", "misc"]
  description = "Ein Website über das was funktioniert."

# [params.author]
  # headline = ""
  # bio = ""
