languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

[params]
  mainSections = ["essay", "guide", "review", "project", "misc"]
  description = "A blog about what works."

# [params.author]
  # headline = ""
  # bio = ""
