name: blog
root: /home/jneidel/code/blog
windows:
  - vim: vim
  - zsh:
      layout: 278d,151x33,0,0[151x12,0,0,35,151x20,0,13,36]
      panes:
        - $BROWSER http://localhost:1313 & hugo server -D -p 1313 --navigateToChanged
        -
  - lf: lf
  - lf: lf
